export interface TaskDef {
  id: string;
  title: string;
  concept: string;
  theoryText: string;
  keyTerms?: { term: string; definition: string }[];
  practical: {
    type:
      | "mapper"
      | "server-audit"
      | "story-adventure"
      | "comparison"
      | "card-sorting"
      | "inspector"
      | "terminal-audit"
      | "drag-drop"
      | "math-console"
      | "graph-matcher"
      | "validator-terminal";
    title: string;
    setupText: string;
    question: string;
    correctAnswer: string; // The verification flag
    debriefText: string;
    inputs?: { label: string; placeholder: string; key: string }[];
    choices?: string[];
  };
}

export interface ModuleDef {
  id: number;
  title: string;
  topic: string;
  stageName: string;
  iconName: "horizon" | "sunrise" | "solar-rise" | "scorch" | "peak" | "descent" | "twilight" | "night";
  color: string;
  angle: number;
  description: string;
  rocketComponent: string;
  tasks: TaskDef[];
}

export const MERCURY_CURRICULUM: ModuleDef[] = [
  {
    id: 1,
    title: "MODULE 01",
    topic: "Why Does Blockchain Exist?",
    stageName: "Dark Horizon",
    iconName: "horizon",
    color: "#22d3ee",
    angle: -90,
    rocketComponent: "ðŸ§± Launch Platform",
    description: "Audit centralized command routing database to isolate systemic vulnerabilities and discover why decentralization is required.",
    tasks: [] // Module 1 is handled by the existing custom React components
  },
  {
    id: 2,
    title: "MODULE 02",
    topic: "Transactions & Digital Ledgers",
    stageName: "First Light",
    iconName: "sunrise",
    color: "#10b981",
    angle: -45,
    rocketComponent: "â›½ Fuel Tank",
    description: "Examine transaction payloads, audit append-only digital ledgers, trace the transaction lifecycle, and act as a mempool gatekeeper.",
    tasks: [
      {
        id: "task2_1",
        title: "Task 2.1 â€” What is a Transaction?",
        concept: "The basic unit of data",
        theoryText: "In a blockchain, a transaction is a signed message that requests a change to the ledger's state. It represents a transfer of value or data from one account to another.\n\nUnlike traditional bank transactions, which are stored behind proprietary firewall software, blockchain transactions are openly structured and readable by anyone. Every transaction contains: Sender (Source Account), Receiver (Destination Account), Amount/Data, Transaction Fee, and a unique Transaction ID (TxID) generated by hashing the payload.",
        keyTerms: [
          { term: "Sender", definition: "The public address of the account initiating the transaction." },
          { term: "Receiver", definition: "The public address of the destination account." },
          { term: "Transaction ID (TxID)", definition: "A unique 64-character alphanumeric string generated by hashing the transaction data." }
        ],
        practical: {
          type: "inspector",
          title: "Visual Transaction Payload Dissector",
          setupText: "Analyze the raw JSON transaction payload shown below to identify its core parameters.",
          question: "Extract and paste the fields from the JSON below: Sender Address, Receiver Address, Transaction ID (TxID), and Sequence Number.",
          correctAnswer: "G_ALPHA_STATION_77:G_BETA_RECON_89:4b87fa12ce09a888d3f10900bba81236ea77bd10129bcce0128912efcc429a1b:48291",
          debriefText: "Every blockchain explorer works by parsing transactions exactly like this. By extracting the sender, receiver, assets, and TxID, we can audit any ledger account without asking permission.",
          inputs: [
            { label: "Sender (Source Account)", placeholder: "e.g. G_ALPHA_STATION_77", key: "sender" },
            { label: "Receiver (Destination)", placeholder: "e.g. G_BETA_RECON_89", key: "receiver" },
            { label: "Transaction ID (TxID)", placeholder: "64-character hash", key: "txid" },
            { label: "Sequence Number", placeholder: "e.g. 48291", key: "seq" }
          ]
        }
      },
      {
        id: "task2_2",
        title: "Task 2.2 â€” The Digital Ledger & Bookkeeping",
        concept: "Append-only databases",
        theoryText: "Traditional databases override account balances in place (e.g. changing 500 to 9000). Blockchains are append-only ledgers. You cannot delete or overwrite past actions. Instead, the ledger is a continuous, chronological record of every transaction that has ever happened since day one (the Genesis block).\n\nTo calculate your current balance, a node scans the entire transaction history from the beginning, adding all incoming and subtracting all outgoing payments. This makes auditability absolute.",
        keyTerms: [
          { term: "Append-Only", definition: "A database style where data can only be added, never deleted or updated." },
          { term: "Genesis Block", definition: "The first block in a blockchain, setting the starting parameters." }
        ],
        practical: {
          type: "terminal-audit",
          title: "Audit the Oxygen Ledger Log",
          setupText: "Look at the append-only logs below:\n\n[Tx 0] Genesis Account -> Mint 1000 Oxygen to Station_Alpha\n[Tx 1] Station_Alpha -> Send 300 Oxygen to Station_Beta\n[Tx 2] Station_Alpha -> Send 200 Oxygen to Station_Gamma\n[Tx 3] Station_Beta -> Send 100 Oxygen to Station_Gamma\n[Tx 4] Station_Gamma -> Send 50 Oxygen to Station_Alpha\n[Tx 5] Station_Beta -> Send 50 Oxygen to Station_Alpha",
          question: "Calculate the current balances of all three stations. Enter the values in the inputs below (e.g. format: 600, 150, 250).",
          correctAnswer: "600:150:250",
          debriefText: "You just computed account balances exactly like a blockchain validator node does. By scanning the history sequentially, the system computes the exact state of balances without storing state as an easily mutable single number.",
          inputs: [
            { label: "Station_Alpha Balance", placeholder: "Calculate Alpha", key: "alpha" },
            { label: "Station_Beta Balance", placeholder: "Calculate Beta", key: "beta" },
            { label: "Station_Gamma Balance", placeholder: "Calculate Gamma", key: "gamma" }
          ]
        }
      },
      {
        id: "task2_3",
        title: "Task 2.3 â€” The Transaction Lifecycle: From Click to Record",
        concept: "The transaction pipeline",
        theoryText: "A transaction does not jump directly into the blockchain the moment you click 'Send'. It goes through a multi-stage validation pipeline:\n\n1. Transaction is created (constructed as a payload).\n2. Signed by the sender's private key.\n3. Broadcasted/submitted to the peer-to-peer network.\n4. Enters the Mempool (waiting queue).\n5. Verified by validators.\n6. Recorded in a block and appended to the chain.",
        keyTerms: [
          { term: "Mempool", definition: "A temporary holding area/queue for verified transactions waiting to be processed by block validators." }
        ],
        practical: {
          type: "drag-drop",
          title: "Sequencing the Transaction Pipeline",
          setupText: "Sort the following phases of a transaction's lifecycle from first to last:\n\n[D] Transaction payload is constructed (Source, Destination, Amount)\n[A] User signs transaction with secret key\n[F] Signed transaction is broadcast to the network nodes\n[E] Transaction sits in the pending queue (Mempool)\n[B] Validators verify the transaction signature and account balances\n[C] Transaction is bundled into a block and appended to the ledger",
          question: "Assemble the letters in the correct sequence order (e.g. DAFEBC)",
          correctAnswer: "DAFEBC",
          debriefText: "Correct! If your transaction shows 'Pending' in your wallet, it means it is currently resting in the mempool waiting for consensus validators to execute it.",
          inputs: [
            { label: "Sequence Code", placeholder: "6-letter code e.g. DAFEBC", key: "seq" }
          ]
        }
      },
      {
        id: "task2_4",
        title: "Task 2.4 â€” Valid vs. Invalid Transactions",
        concept: "Preventing double-spending",
        theoryText: "To keep the ledger clean, every node evaluates pending transactions against strict validation rules:\n\n1. Sufficient Balance: Does the sender have enough funds to cover the amount + fee?\n2. Authentic Signature: Is the signature valid for the source public key?\n3. Correct Sequence: Is the order correct to prevent replay attacks?\n\nDouble Spending occurs when a user tries to spend the same funds twice simultaneously. Blockchain nodes reject the duplicate transaction due to insufficient balance or sequence rules.",
        practical: {
          type: "validator-terminal",
          title: "Mempool Gatekeeper Terminal",
          setupText: "Current Account Balances:\n- G_ALPHA: 100 Oxygen\n- G_BETA: 20 Oxygen\n- G_GAMMA: 5 Oxygen\n\nPending Queue:\n1. G_ALPHA sends 95 to G_BETA (Fee: 2) -> Total 97. (Alpha balance is 100)\n2. G_GAMMA sends 10 to G_ALPHA (Fee: 1) -> Total 11. (Gamma balance is 5)\n3. G_BETA sends 20 to G_GAMMA (Fee: 1) -> Total 21. (Beta balance is 20)\n4. G_BETA sends 15 to G_ALPHA (Fee: 1) -> Total 16. (Beta balance is 20)\n5. G_ALPHA sends 150 to G_GAMMA (Fee: 2) -> Total 152. (Alpha balance is 100)",
          question: "Evaluate each transaction. Approve (1) if it is valid, or Reject (0) if it is invalid. Enter the 5-digit binary result (e.g. 10010).",
          correctAnswer: "10010",
          debriefText: "Correct! By filtering out invalid transactions, nodes preserve ledger accuracy and prevent double spending attempts before they can compromise blockchain history.",
          inputs: [
            { label: "Approvals Code (1=Approve, 0=Reject)", placeholder: "e.g. 10010", key: "code" }
          ]
        }
      },
      {
        id: "task2_5",
        title: "Task 2.5 â€” Chapter Challenge: Transfer Oxygen Supplies",
        concept: "Ledger transaction auditing",
        theoryText: "Three space stations are suffering oxygen supply failures. You must validate the transaction ledger queue to identify any invalid transfers and calculate their final balances before the fuel tank systems can be calibrated.",
        practical: {
          type: "server-audit",
          title: "Auditing Station Ledger Allocations",
          setupText: "Initial Balances:\n- Station_A: 50 units\n- Station_B: 30 units\n- Station_C: 20 units\n\nTransaction Log Queue:\n1. Station_A -> 20 units -> Station_B\n2. Station_B -> 40 units -> Station_C\n3. Station_C -> 50 units -> Station_A\n4. Station_A -> 45 units -> Station_B\n5. Station_B -> 60 units -> Station_C",
          question: "Input the invalid transaction index (1-5) and the final balances of Station A, B, and C in the fields below.",
          correctAnswer: "5:35:55:10",
          debriefText: "Excellent work! The Fuel Tank is successfully installed and filled. In the next module, you will learn how these individual transactions are grouped and structured into blocks.",
          inputs: [
            { label: "Invalid Transaction Number", placeholder: "e.g. 5", key: "invalid_tx" },
            { label: "Station_A Final Balance", placeholder: "e.g. 35", key: "bal_a" },
            { label: "Station_B Final Balance", placeholder: "e.g. 55", key: "bal_b" },
            { label: "Station_C Final Balance", placeholder: "e.g. 10", key: "bal_c" }
          ]
        }
      }
    ]
  },
  {
    id: 3,
    title: "MODULE 03",
    topic: "Blocks & Blockchain Structure",
    stageName: "Solar Rise",
    iconName: "solar-rise",
    color: "#f59e0b",
    angle: 0,
    rocketComponent: "ðŸ”¥ Combustion Chamber",
    description: "Learn block header metadata structures, audit genesis configurations, calculate TPS throughput, and reconstruct chronological blockchains.",
    tasks: [
      {
        id: "task3_1",
        title: "Task 3.1 â€” What is a Block? (Header and Data)",
        concept: "Bundling transactions in blocks",
        theoryText: "Validating transactions one-by-one is highly inefficient. Instead, blockchains bundle verified transactions into a single container called a block. A block contains:\n\n1. Block Header (Metadata): height, previous block hash, timestamp, and mining nonce.\n2. Block Body: The list of transactions included in the block.\n\nBy separating headers from transaction details, nodes can audit blockchain history rapidly by checking only headers.",
        practical: {
          type: "inspector",
          title: "Block Explorer Payload Dissector",
          setupText: "Analyze the block JSON packet below:\n\n{\n  \"header\": {\n    \"block_height\": 849,\n    \"timestamp\": 1782294910,\n    \"prev_block_id\": \"0000a39f12bc8e0018f2bb7c71e892cbb87a9bc19cce01ef\",\n    \"nonce\": 38491\n  },\n  \"body\": {\n    \"transactions\": [\n      {\"txid\": \"ab12\", \"amount\": 100},\n      {\"txid\": \"cd34\", \"amount\": 50},\n      {\"txid\": \"ef56\", \"amount\": 10},\n      {\"txid\": \"gh78\", \"amount\": 200}\n    ]\n  }\n}",
          question: "Extract Block Height, Transactions Count, and the Previous Block ID from the payload.",
          correctAnswer: "849:4:0000a39f12bc8e0018f2bb7c71e892cbb87a9bc19cce01ef",
          debriefText: "Excellent! You've separated metadata (the header) from execution data (the body). This separation is the basis for blockchain scalability and light client verification.",
          inputs: [
            { label: "Block Height", placeholder: "e.g. 849", key: "height" },
            { label: "Number of Transactions", placeholder: "e.g. 4", key: "txcount" },
            { label: "Previous Block ID Hash", placeholder: "Hash code", key: "prev_hash" }
          ]
        }
      },
      {
        id: "task3_2",
        title: "Task 3.2 â€” The Genesis Block",
        concept: "The origin block",
        theoryText: "The first block in a blockchain is called the Genesis Block (or Block #0). Since it has no parent, its Previous Block Reference field is hardcoded to all zeros. The Genesis block parameters are hardcoded directly into the node software, setting the initial state of account allocations and network properties.",
        practical: {
          type: "inspector",
          title: "Genesis File Inspector",
          setupText: "Audit the genesis.json config below:\n\n{\n  \"block_height\": 0,\n  \"prev_block_id\": \"000000000000000000000000000000000000000000000000\",\n  \"timestamp\": 1782200000,\n  \"network_id\": \"MERCURY_TESTNET_GENESIS\",\n  \"initial_allocation\": {\n    \"G_FOUNDING_TREASURY\": 1000000,\n    \"G_LAUNCH_SYSTEMS\": 500000\n  },\n  \"secret_message\": \"Mercury Launchpad Coordinates Unlocked 2026\"\n}",
          question: "Retrieve Previous Block ID, Network ID, and the Secret Message.",
          correctAnswer: "000000000000000000000000000000000000000000000000:MERCURY_TESTNET_GENESIS:Mercury Launchpad Coordinates Unlocked 2026",
          debriefText: "Correct! The Genesis Block sets the rules. All future blocks build chronologically on top of this single configuration footprint.",
          inputs: [
            { label: "Previous Block ID", placeholder: "All zeros", key: "prev_id" },
            { label: "Network ID", placeholder: "Network identifier", key: "network_id" },
            { label: "Secret Message String", placeholder: "Paste string", key: "secret_msg" }
          ]
        }
      },
      {
        id: "task3_3",
        title: "Task 3.3 â€” Block Size & Network Capacity",
        concept: "TPS throughput calculations",
        theoryText: "Block sizes are limited to prevent network congestion, storage strain, and high processing requirements. To compute transaction throughput, we calculate: \n\nTPS = (Max Transactions Per Block) / (Block Time in Seconds)\n\nLet's apply this throughput formula to calibrate optimal telemetry speeds.",
        practical: {
          type: "math-console",
          title: "Throughput Calculator Console",
          setupText: "Calculate the maximum TPS for each network topology configuration:\n\nNetwork A:\n- Avg Transaction Size: 500 bytes\n- Block Size Limit: 1,000,000 bytes (1 MB)\n- Block Time: 10 seconds\n\nNetwork B:\n- Avg Transaction Size: 250 bytes\n- Block Size Limit: 2,000,000 bytes (2 MB)\n- Block Time: 5 seconds\n\nNetwork C:\n- Avg Transaction Size: 1,000 bytes\n- Block Size Limit: 1,000,000 bytes (1 MB)\n- Block Time: 100 seconds",
          question: "Enter the maximum TPS values for Network A, B, and C.",
          correctAnswer: "200:1600:10",
          debriefText: "Correct! Block configurations define capacity. Stellar keeps transaction sizes small and block times short (5s) to allow high throughput.",
          inputs: [
            { label: "Network A Max TPS", placeholder: "Calculate TPS", key: "tps_a" },
            { label: "Network B Max TPS", placeholder: "Calculate TPS", key: "tps_b" },
            { label: "Network C Max TPS", placeholder: "Calculate TPS", key: "tps_c" }
          ]
        }
      },
      {
        id: "task3_4",
        title: "Task 3.4 â€” The Chain: Linking Blocks Chronologically",
        concept: "Header back-pointers",
        theoryText: "Blocks connect sequentially using the Previous Block Reference in their headers. Block #1 points to Block #0. Block #2 points to Block #1. This linkage creates a rigid timeline. You cannot insert or swap blocks; any tampering breaks the pointers, letting nodes know history was compromised.",
        practical: {
          type: "drag-drop",
          title: "Sequencing the Chain Pointers",
          setupText: "Sort these 4 blocks from Genesis (height 0) to Block #3 based on their properties:\n\n- Block W | Height: 3, Previous Block Hash: 0xCC\n- Block X | Height: 1, Previous Block Hash: 0xAA (Hash of Block Z)\n- Block Y | Height: 2, Previous Block Hash: 0xBB (Hash of Block X)\n- Block Z | Height: 0, Previous Block Hash: 0x00 (Genesis Block, Hash: 0xAA)",
          question: "Assemble the letters of the sorted blocks (Genesis to Height 3).",
          correctAnswer: "ZXYW",
          debriefText: "Correct! Each block acts as a link. By validating that height N points to height N-1, nodes can trace a direct, unbroken line of historical events back to the genesis block.",
          inputs: [
            { label: "Sort Sequence (e.g. ZXYW)", placeholder: "4 letters", key: "seq" }
          ]
        }
      },
      {
        id: "task3_5",
        title: "Task 3.5 â€” Chapter Challenge: Repair the Broken Space Log",
        concept: "Rebuilding chain structures",
        theoryText: "Solar flares have corrupted block storage logs. Sort the scrambled blocks to restore chronology and calculate Station A's remaining fuel balance after Block 3 is processed.",
        practical: {
          type: "server-audit",
          title: "Scrambled Block Reconstructor",
          setupText: "Scrambled Blocks:\n- Block ID Gamma | Height: 2, Prev: 0xALPHA. (Tx: Station_B -> 50 -> Station_C)\n- Block ID Delta | Height: 3, Prev: 0xGAMMA. (Tx: Station_C -> 10 -> Station_A)\n- Block ID Beta | Height: 0, Prev: 0x0000. (Tx: Genesis -> 1000 -> Station_A)\n- Block ID Alpha | Height: 1, Prev: 0xBETA. (Tx: Station_A -> 100 -> Station_B)",
          question: "Enter the sorted block sequence (Beta, Alpha, Gamma, Delta) and the final balance of Station A.",
          correctAnswer: "Beta:Alpha:Gamma:Delta:910",
          debriefText: "Superb assembly! The blocks are sorted, the log is repaired, and the Combustion Chamber is locked into place. Next, we will cover how block data is securely fingerprinted and protected from tampering.",
          inputs: [
            { label: "Block 0 (Genesis) ID", placeholder: "e.g. Beta", key: "b0" },
            { label: "Block 1 ID", placeholder: "e.g. Alpha", key: "b1" },
            { label: "Block 2 ID", placeholder: "e.g. Gamma", key: "b2" },
            { label: "Block 3 ID", placeholder: "e.g. Delta", key: "b3" },
            { label: "Station A Final Fuel Balance", placeholder: "e.g. 910", key: "bal_a" }
          ]
        }
      }
    ]
  },
  {
    id: 4,
    title: "MODULE 04",
    topic: "Hashing & Data Integrity",
    stageName: "Scorch Zone",
    iconName: "scorch",
    color: "#f43f5e",
    angle: 45,
    rocketComponent: "âš™ï¸ Rocket Engine",
    description: "Learn cryptographic hash parameters, investigate the avalanche effect, compare hashing to encryption, and run checksum integrity audits.",
    tasks: [
      {
        id: "task4_1",
        title: "Task 4.1 â€” What is a Cryptographic Hash?",
        concept: "The digital fingerprint",
        theoryText: "A cryptographic hash function takes an input of any size and converts it into a fixed-length string of hex characters. Key properties:\n\n1. Deterministic: Same input yields the same hash.\n2. Fixed-Length: SHA-256 always yields 64 hex characters.\n3. One-Way: Impossible to reverse the hash back into original data.\n4. Collision Resistant: Impossible to find two different inputs that map to the same hash.",
        practical: {
          type: "terminal-audit",
          title: "Hash Generator Console",
          setupText: "Use the terminal database tool to hash configurations. Run 'sha256' on the telemetry initialization string:\n\nInput String: \"Blockchain is secure\"",
          question: "Calculate the SHA-256 hash of \"Blockchain is secure\" and input its FIRST 8 characters (lowercase).",
          correctAnswer: "8e9ffc5d",
          debriefText: "You've generated your first cryptographic fingerprints. Notice how both a single word and a full sentence yield a hash of exactly 64 characters (256 bits).",
          inputs: [
            { label: "First 8 characters of SHA-256", placeholder: "e.g. 8e9ffc5d", key: "hash8" }
          ]
        }
      },
      {
        id: "task4_2",
        title: "Task 4.2 â€” The Avalanche Effect",
        concept: "Amplifying small changes",
        theoryText: "A secure hash function requires the avalanche effect: changing even a single bit in the input causes the output hash to change completely. This prevents hackers from guessing inputs incrementally.",
        practical: {
          type: "drag-drop",
          title: "The Avalanche Detector",
          setupText: "Compare the inputs and their resulting hashes:\n\nInput C: \"Launch the rocket\"\nInput D: \"Launch the rocket.\"\n\nHash C: \"3a4f89be...\"\nHash D: \"c8d9e2b1...\"",
          question: "What is the exact character that was appended to Input C to cause a completely different hash in Input D?",
          correctAnswer: ".",
          debriefText: "Correct! The addition of a single period (.) caused a massive, random avalanche shift, making it impossible to deduce the original data structure from the hash comparison.",
          inputs: [
            { label: "Appended Character", placeholder: "e.g. .", key: "char" }
          ]
        }
      },
      {
        id: "task4_3",
        title: "Task 4.3 â€” Hashing vs. Encryption",
        concept: "One-way vs two-way operations",
        theoryText: "Hashing is a one-way mathematical function used for integrity audits (no key is required; fixed-length output). Encryption is a two-way function used for private communication (requires a key to encrypt/decrypt; output size grows with input).",
        practical: {
          type: "drag-drop",
          title: "Categorize the Cryptographic Tool",
          setupText: "Sort these 6 statements based on whether they describe Hashing (H) or Encryption (E):\n\n1. Used to store user passwords on a database so even administrators cannot read them.\n2. Used to send private messages that only the holder of a private key can read.\n3. Generates a fixed 64-character string regardless of how large the input is.\n4. Requires a secret key to unlock and recover the original readable data.\n5. A mathematical process that cannot be reversed under any computing power.\n6. The output length grows larger as you encrypt larger files.",
          question: "Assemble the letters H (Hashing) and E (Encryption) for statements 1 to 6 in order (e.g. HEHEHE).",
          correctAnswer: "HEHEHE",
          debriefText: "Correct! Remember: Hashing is for verification (integrity). Encryption is for privacy (confidentiality).",
          inputs: [
            { label: "Answer Code", placeholder: "6-letter code", key: "code" }
          ]
        }
      },
      {
        id: "task4_4",
        title: "Task 4.4 â€” Detect the Alien Message",
        concept: "Checksum integrity checks",
        theoryText: "Because hash outputs are deterministic, we can verify file integrity. By comparing the calculated hash of a received file against its expected hash, we can instantly detect if a transmission has been altered.",
        practical: {
          type: "terminal-audit",
          title: "Tampered Transmission Audit",
          setupText: "We received 4 signals. The control hashes are:\n- Msg 1 Expected: f129a008 (hash of \"Sector 5 is clear\")\n- Msg 2 Expected: e5c7a911 (hash of \"Oxygen status: 98%\")\n- Msg 3 Expected: d8d9b1c2 (hash of \"Maintain speed at 5000 km/h\")\n- Msg 4 Expected: a8e9f1a2 (hash of \"Initiating landing sequence\")\n\nActual received signals on disk:\n- Msg 1: \"Sector 5 is clear\"\n- Msg 2: \"Oxygen status: 98%\"\n- Msg 3: \"Maintain speed at 5000 km/h\"\n- Msg 4: \"Initiating Landing Sequence\"",
          question: "Calculate the hashes of the received strings to find the corrupted transmission index (1-4).",
          correctAnswer: "4",
          debriefText: "Excellent detective work. Hashing \"Initiating Landing Sequence\" (with capital L and S) produces a mismatched hash, exposing alien tampering.",
          inputs: [
            { label: "Corrupted Message Index (1-4)", placeholder: "e.g. 4", key: "corrupt_idx" }
          ]
        }
      },
      {
        id: "task4_5",
        title: "Task 4.5 â€” Chapter Challenge: SHA-256 Calibration",
        concept: "Verifying systems configurations",
        theoryText: "Calibrate the engine log configurations by matching the active instructions to their corresponding validation hashes to initialize the Rocket Engine.",
        practical: {
          type: "server-audit",
          title: "Engine Hash Calibration Matcher",
          setupText: "Instructions:\n- Alpha: \"fuel_val_42\"\n- Beta: \"ignition_active\"\n- Gamma: \"stabilizers_on\"\n\nEngine Check Hashes:\n- Hash 1: \"6d39369f\" (matches hash(\"ignition_active\"))\n- Hash 2: \"e0e7a1cb\" (matches hash(\"stabilizers_on\"))\n- Hash 3: \"7a0b82f1\" (matches hash(\"fuel_val_42\"))",
          question: "Identify the matching inputs (Alpha / Beta / Gamma) for Hash 1, 2, and 3.",
          correctAnswer: "Beta:Gamma:Alpha",
          debriefText: "Magnificent calibration! The Rocket Engine is fully built and installed. Next, we will cover how these hashes link blocks together in a secure chain.",
          inputs: [
            { label: "Input matching Hash 1", placeholder: "Alpha, Beta, or Gamma", key: "h1" },
            { label: "Input matching Hash 2", placeholder: "Alpha, Beta, or Gamma", key: "h2" },
            { label: "Input matching Hash 3", placeholder: "Alpha, Beta, or Gamma", key: "h3" }
          ]
        }
      }
    ]
  },
  {
    id: 5,
    title: "MODULE 05",
    topic: "How Blocks Are Connected",
    stageName: "Solar Peak",
    iconName: "peak",
    color: "#a855f7",
    angle: 90,
    rocketComponent: "ðŸš€ Main Engine Nozzle",
    description: "Audit parent hash back-links, trigger chain reaction domino effects, hash block headers, and repair broken transaction ledger links.",
    tasks: [
      {
        id: "task5_1",
        title: "Task 5.1 â€” The Previous Block Hash Link",
        concept: "The block hashing pointer",
        theoryText: "How are blocks linked? Block N includes the hash of Block N-1 in its own header data before its own block hash is computed. This mathematical dependency seals the history. Altering Block N-1 forces a recalculation of Block N's hash, warning all nodes that the links are broken.",
        practical: {
          type: "inspector",
          title: "Chain Pointer Inspector",
          setupText: "Verify the link between Block 1 and Block 2:\n\n- Block 1 Hash: 0000a12fbc99\n- Block 2 Hash: 0000e39a88cd (prev_block_id: 0000a12fbc99)\n- Block 3 Hash: 0000b21fa7e1 (prev_block_id: 0000e39a88cd)",
          question: "What is the exact field name in Block 2's header that links it back to Block 1?",
          correctAnswer: "prev_block_id",
          debriefText: "Correct! The previous block reference acts as a cryptographic tie. If a parent block changes, its child immediately detects the broken reference.",
          inputs: [
            { label: "Field Name", placeholder: "prev_block_id", key: "field" }
          ]
        }
      },
      {
        id: "task5_2",
        title: "Task 5.2 â€” Block Dependency & The Domino Effect",
        concept: "Cascading block invalidation",
        theoryText: "What happens if a transaction in Block 2 is tampered with? The hash of Block 2 changes immediately. Block 3's prev_block_id reference is now broken. To fix this, Block 3's header must be updated, which changes Block 3's hash, breaking Block 4. This domino cascade makes historical fraud easily discoverable.",
        practical: {
          type: "comparison",
          title: "Domino Effect Pipeline Simulator",
          setupText: "Tamper with Block 2 in an active 5-block chain:\n\n`Block 1 -> Block 2 -> Block 3 -> Block 4 -> Block 5`",
          question: "Which blocks downstream turn red and fail verification? (Enter 'Block 2,3,4,5' or 'All of them')",
          correctAnswer: "All of them",
          debriefText: "Correct! By checking that block hashes and previous references match all the way up the chain, any node can instantly verify the integrity of the entire ledger history in milliseconds.",
          inputs: [
            { label: "Invalidated Blocks", placeholder: "All of them", key: "blocks" }
          ]
        }
      },
      {
        id: "task5_3",
        title: "Task 5.3 â€” Hashing a Block: Header Calculation",
        concept: "Creating block seals",
        theoryText: "A block's hash is computed by concatenating and hashing its header fields:\n\nHash = SHA256(Block Height + Timestamp + Previous Block ID + Tx Root + Nonce)",
        practical: {
          type: "terminal-audit",
          title: "Block Hash Calculator",
          setupText: "Concatenate and hash the block header parameters:\n\n- height: \"5\"\n- timestamp: \"1782200500\"\n- prev_block_id: \"0000a9b8\"\n- tx_root: \"f82e3c09\"\n- nonce: \"48291\"\n\nString format: height + timestamp + prev_block_id + tx_root + nonce",
          question: "Run 'sha256' on the concatenated string to find the block hash. Enter the FIRST 8 characters of the resulting hash.",
          correctAnswer: "d4d98a00",
          debriefText: "You've manually calculated a block hash. In production networks, this calculation is performed by validator nodes millions of times per second to seal ledgers.",
          inputs: [
            { label: "First 8 characters of Block Hash", placeholder: "e.g. d4d98a00", key: "hash8" }
          ]
        }
      },
      {
        id: "task5_4",
        title: "Task 5.4 â€” Chain Integrity and Decentralized Security",
        concept: "Longest chain rule",
        theoryText: "An attacker can recalculate hashes on their local machine to validate their fraud. However, they cannot force the network to accept it. Every node keeps a copy of the ledger. Network rules state: 'The longest valid chain is the real chain'. The attacker would need to compute faster than the majority of the honest network combined (51% attack) to overwrite history.",
        practical: {
          type: "math-console",
          title: "Downstream Impact Audit",
          setupText: "A chain contains: Block 0 -> Block 1 -> Block 2 -> Block 3 -> Block 4 -> Block 5.\n\nAn attacker compromises Block 3 and alters a transaction entries payload.",
          question: "1) Which block index's hash changes first?\n2) Does Block 2's hash change? (yes/no)\n3) Which blocks downstream fail validation because of the broken link? (list separated by commas)",
          correctAnswer: "3:no:4,5",
          debriefText: "Correct. Changes propagate forward, not backward. Block 2 remains perfectly valid, while Block 3, 4, and 5 are invalidated.",
          inputs: [
            { label: "First altered hash block index", placeholder: "e.g. 3", key: "first" },
            { label: "Does Block 2 change? (yes/no)", placeholder: "yes/no", key: "b2" },
            { label: "Broken downstream blocks", placeholder: "e.g. 4,5", key: "broken" }
          ]
        }
      },
      {
        id: "task5_5",
        title: "Task 5.5 â€” Chapter Challenge: Repair the Galactic Blockchain",
        concept: "Repairing hash references",
        theoryText: "Alien saboteurs have corrupted Block #2 on the ledger. You must locate the tampered block, calculate the repair hashes, and realign the rocket nozzle.",
        practical: {
          type: "server-audit",
          title: "Sabotaged Ledger Repair",
          setupText: "Ledger Log:\n- Block #0 (Genesis) | Hash: 0xAAAA, Prev: 0x0000\n- Block #1 | Hash: 0xBBBB, Prev: 0xAAAA\n- Block #2 (Tampered Data) | Hash: 0x9999 (should be calculated from prev: 0xBBBB and data: \"val_42\")\n- Block #3 (Failed Link) | Hash: 0xDDDD (prev: 0xCCCC, but parent reports 0x9999)",
          question: "Which block index was tampered with? And if restoring Block 2's data returns its hash to 0xCCCC, what value must be in Block 3's prev_block_id field to repair the link?",
          correctAnswer: "2:0xCCCC",
          debriefText: "Excellent repair sequence! The Engine Nozzle is installed, and the chain integrity is restored. In the next module, you will learn who controls these networks.",
          inputs: [
            { label: "Tampered Block Index", placeholder: "e.g. 2", key: "tampered_idx" },
            { label: "Block 3 prev_block_id repair value", placeholder: "e.g. 0xCCCC", key: "repair_hash" }
          ]
        }
      }
    ]
  },
  {
    id: 6,
    title: "MODULE 06",
    topic: "Decentralization & Distributed Networks",
    stageName: "Solar Descent",
    iconName: "descent",
    color: "#f97316",
    angle: 135,
    rocketComponent: "ðŸ“¡ Communication System",
    description: "Map network topologies, audit node configuration Sync parameters, simulate Gossip transmission routing, and calculate Byzantine Fault tolerance.",
    tasks: [
      {
        id: "task6_1",
        title: "Task 6.1 â€” Centralized, Decentralized, and Distributed Topologies",
        concept: "Network configurations",
        theoryText: "There are three primary network layout topologies:\n\n1. Centralized: All clients connect to a single central server. The server holds all data. Single point of failure.\n2. Decentralized: A collection of local servers or 'hubs' connect clusters of clients.\n3. Distributed (Mesh): Every node connects directly to multiple other nodes. Equal peers. No central hubs.",
        practical: {
          type: "math-console",
          title: "Network Topology Builder",
          setupText: "A group of space stations wants to form a fully meshed distributed network where every node connects directly to every other node.",
          question: "Calculate the total number of connection links required to make a 6-node network fully meshed.",
          correctAnswer: "15",
          debriefText: "Correct! A fully meshed distributed network has high redundancy. It requires many more connection links, but it eliminates any single point of attack or failure.",
          inputs: [
            { label: "Total connection links", placeholder: "e.g. 15", key: "links" }
          ]
        }
      },
      {
        id: "task6_2",
        title: "Task 6.2 â€” What is a Blockchain Node?",
        concept: "Node client properties",
        theoryText: "A node is a computer running the blockchain's client software client (like Stellar-Core). Nodes maintain the network. Types of nodes:\n\n1. Full Nodes: Download and keep the complete ledger history and audit all entries.\n2. Light Nodes: Only download block headers and rely on full nodes to verify transaction details.\n3. Validator Nodes: Participate in consensus voting to add blocks next.",
        practical: {
          type: "inspector",
          title: "Node Configuration Auditor",
          setupText: "Audit the active node-config.json configuration file below:\n\n{\n  \"node_id\": \"MERCURY_VALIDATOR_09\",\n  \"client_version\": \"v1.4.2\",\n  \"network\": \"mercury_testnet\",\n  \"storage\": {\n    \"sync_mode\": \"full_history\",\n    \"keep_tx_index\": true,\n    \"pruning_enabled\": false\n  },\n  \"consensus\": {\n    \"participate_in_voting\": true,\n    \"quorum_set\": [\"NODE_ALPHA\", \"NODE_BETA\", \"NODE_GAMMA\"]\n  },\n  \"max_peers\": 40\n}",
          question: "1) Is this node syncing 'full' or 'light' history?\n2) Does it vote in consensus? (yes/no)\n3) What is the node ID?",
          correctAnswer: "full:yes:MERCURY_VALIDATOR_09",
          debriefText: "Correct. This is a Full Validator Node. It stores the full ledger history and actively participates in consensus voting to secure the network.",
          inputs: [
            { label: "Sync mode type", placeholder: "full / light", key: "sync" },
            { label: "Participates in consensus? (yes/no)", placeholder: "yes / no", key: "vote" },
            { label: "Node ID String", placeholder: "e.g. MERCURY_VALIDATOR_09", key: "id" }
          ]
        }
      },
      {
        id: "task6_3",
        title: "Task 6.3 â€” Peer-to-Peer Communication & Gossip Protocols",
        concept: "Gossip validation routing",
        theoryText: "How do nodes share transactions? When Node A gets a transaction, it validates it and gossips (forwards) it to its direct peers, who forward to their peers. Crucially, nodes do not forward invalid transactions. If a transaction fails validation, it is blocked immediately.",
        practical: {
          type: "graph-matcher",
          title: "Gossip Transmission Simulator",
          setupText: "We have 10 nodes. You submitted a transaction on Node 1, which propagates to all nodes. Then, you submit an invalid transaction (e.g. double spend) on Node 4.",
          question: "Which node index will detect the invalid transaction and reject it, stopping it from propagating to the rest of the network?",
          correctAnswer: "4",
          debriefText: "Because every node is an independent auditor, bad data is blocked at the first point of entry, preventing network contamination.",
          inputs: [
            { label: "Rejecting Node Index", placeholder: "e.g. 4", key: "node_idx" }
          ]
        }
      },
      {
        id: "task6_4",
        title: "Task 6.4 â€” Fault Tolerance: Surviving Node Failures",
        concept: "Network consensus security thresholds",
        theoryText: "How many nodes can go offline before the network halts? \n- Crash Fault Tolerance (CFT): Needs a simple majority online.\n- Byzantine Fault Tolerance (BFT): Network survives as long as more than 2/3 of nodes are honest. If f nodes are malicious/offline, the network must contain at least 3f + 1 nodes to reach consensus.",
        practical: {
          type: "math-console",
          title: "Consensus Security Calculator",
          setupText: "A satellite validator network has:\n- Total configured nodes: 12\n- Consensus type: Byzantine Fault Tolerant (3f + 1 rule)\n- Current network state: 9 nodes online, 3 nodes offline",
          question: "1) What percentage of nodes are online?\n2) What is the maximum number of malicious nodes (f) this 12-node network can tolerate?",
          correctAnswer: "75:3",
          debriefText: "Excellent. At 75% online, the network is well within its Byzantine Fault Tolerance thresholds, allowing safe operation even with 3 offline validator nodes.",
          inputs: [
            { label: "Percentage of nodes online", placeholder: "e.g. 75", key: "percent" },
            { label: "Max tolerated malicious nodes (f)", placeholder: "e.g. 3", key: "f_value" }
          ]
        }
      },
      {
        id: "task6_5",
        title: "Task 6.5 â€” Chapter Challenge: Save Mercury's Network",
        concept: "Deploying fault-tolerant nodes",
        theoryText: "The central server is down due to solar storm interference. Deploy 5 backup nodes across Stations Alpha, Beta, Gamma, Delta, and Epsilon. If a station outage occurs, at least 3 nodes must stay online to maintain consensus.",
        practical: {
          type: "server-audit",
          title: "Distributed Fault-Tolerance Game",
          setupText: "Outage Timeline:\n- Outage 1: Station Alpha goes offline. (4 nodes remain)\n- Outage 2: Station Gamma goes offline. (3 nodes remain)\n- Outage 3: Station Delta goes offline. (2 nodes remain - Consensus Lost!)\n\nLet's compare this to having a single centralized server at Station Alpha.",
          question: "1) At which outage would a centralized server at Alpha have crashed?\n2) With 5 distributed nodes, at which outage does the system finally fail consensus?",
          correctAnswer: "1:3",
          debriefText: "Brilliant network deployment! The Communication System is active and configured. You now understand how distributed networks eliminate central failures.",
          inputs: [
            { label: "Centralized failure outage index", placeholder: "e.g. 1", key: "central_fail" },
            { label: "Distributed failure outage index", placeholder: "e.g. 3", key: "dist_fail" }
          ]
        }
      }
    ]
  },
  {
    id: 7,
    title: "MODULE 07",
    topic: "Consensus & Transaction Validation",
    stageName: "Twilight Zone",
    iconName: "twilight",
    color: "#6366f1",
    angle: 180,
    rocketComponent: "ðŸ§­ Navigation System",
    description: "Solve Byzantine Generals puzzles, compare PoW vs. PoS consensus systems, identify federated quorum cores, and order double-spending transactions.",
    tasks: [
      {
        id: "task7_1",
        title: "Task 7.1 â€” The Consensus Problem & The Byzantine Generals",
        concept: "Reaching agreement with traitors",
        theoryText: "In a P2P network, there is no boss. Consensus protocols resolve agreement between strangers. The Byzantine Generals Problem outlines this: a group of generals must agree on a single plan (Attack or Retreat). Some generals might be traitors who send conflicting orders. Honest generals must reach a consensus as long as more than 2/3 are honest.",
        practical: {
          type: "math-console",
          title: "Byzantine General's Decision",
          setupText: "Commander General Alpha sends order \"ATTACK\" to 3 peer generals:\n- General Beta (Honest) relays \"ATTACK\" to Gamma and Delta.\n- General Gamma (Honest) relays \"ATTACK\" to Beta and Delta.\n- General Delta (Traitor) relays \"RETREAT\" to Beta and \"ATTACK\" to Gamma.",
          question: "1) How many ATTACK votes does Beta receive in total from peers?\n2) How many RETREAT votes does Beta receive?\n3) What is Beta's majority vote decision? (ATTACK / RETREAT)",
          correctAnswer: "2:1:ATTACK",
          debriefText: "Correct! Even with one traitor sending conflicting instructions, the honest majority reaches consensus on the correct battle plan. This is the mathematical basis of Byzantine Fault Tolerance.",
          inputs: [
            { label: "ATTACK votes received", placeholder: "e.g. 2", key: "attack" },
            { label: "RETREAT votes received", placeholder: "e.g. 1", key: "retreat" },
            { label: "Majority Decision", placeholder: "ATTACK / RETREAT", key: "decision" }
          ]
        }
      },
      {
        id: "task7_2",
        title: "Task 7.2 â€” Introduction to Proof of Work & Proof of Stake",
        concept: "Resource-based validation proofs",
        theoryText: "Consensus protocols require nodes to expend real-world resources to prevent Sybil attacks:\n\n1. Proof of Work (PoW): Nodes (miners) compete to solve hard puzzles using massive electricity and hardware power. (Bitcoin)\n2. Proof of Stake (PoS): Nodes (validators) lock up native cryptocurrency tokens as collateral to participate in proposing and voting. (Ethereum)",
        practical: {
          type: "drag-drop",
          title: "Consensus Characteristic Matcher",
          setupText: "Classify these 6 statements as Proof of Work (W) or Proof of Stake (S):\n\n1. Consumes massive electricity to run specialized mining hardware.\n2. Requires validators to lock up native cryptocurrency tokens as collateral.\n3. Probability of building a block depends on your share of the network's hashrate.\n4. Highly energy-efficient and runs on consumer-grade servers.\n5. Requires miners to find a block nonce satisfying a difficulty target.\n6. If validators approve invalid blocks, their locked funds are slashed.",
          question: "Enter the sequence of W (PoW) and S (PoS) for statements 1 to 6 (e.g. WSWSSS).",
          correctAnswer: "WSWSSS",
          debriefText: "Correct! While PoW relies on thermodynamics and hardware, PoS relies on financial incentives and collateral locks to enforce honesty.",
          inputs: [
            { label: "Answer Code", placeholder: "e.g. WSWSSS", key: "code" }
          ]
        }
      },
      {
        id: "task7_3",
        title: "Task 7.3 â€” Introduction to Federated Consensus (Stellar / SCP)",
        concept: "Consensus trust networks",
        theoryText: "Stellar uses the Stellar Consensus Protocol (SCP) based on Federated Byzantine Agreement. Slices of trust are configured: every node selects a set of other nodes they trust (Quorum Slice). When these slices overlap globally, agreement propagates rapidly (5s block times) with near-zero costs.",
        practical: {
          type: "graph-matcher",
          title: "Find the Quorum Overlap",
          setupText: "Analyze the configured quorum trust slices for 5 nodes:\n- Node 1 Trusts: {Node 2, Node 3}\n- Node 2 Trusts: {Node 1, Node 3}\n- Node 3 Trusts: {Node 1, Node 2, Node 4}\n- Node 4 Trusts: {Node 3, Node 5}\n- Node 5 Trusts: {Node 4}",
          question: "Identify the indices of the mutually trusting nodes that form the core quorum (sorted ascending, comma-separated).",
          correctAnswer: "1,2,3",
          debriefText: "You've identified the overlapping consensus slice. In the Stellar network, nodes run by organizations like SDF, universities, and payment gateways overlap to keep the global ledger in lockstep.",
          inputs: [
            { label: "Core Quorum Node List", placeholder: "e.g. 1,2,3", key: "quorum" }
          ]
        }
      },
      {
        id: "task7_4",
        title: "Task 7.4 â€” Resolving Double-Spending Conflicts",
        concept: "Transaction ordering validation",
        theoryText: "Consensus doesn't just check balances; it establishes the exact order of transactions. If a user submits two conflicting payments, validators group them inside a block and assign them a strict index sequence. The first transaction executes, draining the balance; the second is evaluated and rejected.",
        practical: {
          type: "validator-terminal",
          title: "Double-Spend Order Auditor",
          setupText: "Starting Wallet Balance: 100 units\n\nCompeting Transactions in Mempool:\n- Tx Alpha: Sends 80 units to Station_B (Timestamp: 14:02:10.012)\n- Tx Beta: Sends 30 units to Station_C (Timestamp: 14:02:10.015)",
          question: "Which transaction will be accepted (earlier timestamp) and which will be rejected? Enter format: Accepted:Rejected (e.g. Alpha:Beta).",
          correctAnswer: "Alpha:Beta",
          debriefText: "Correct! Because Tx Alpha is processed first, it depletes the account balance to 20 units. Tx Beta is rejected during block evaluation because the sender's balance is insufficient.",
          inputs: [
            { label: "Accepted:Rejected Transaction IDs", placeholder: "e.g. Alpha:Beta", key: "resolution" }
          ]
        }
      },
      {
        id: "task7_5",
        title: "Task 7.5 â€” Chapter Challenge: Galactic Council Decision",
        concept: "Consensus voting verification",
        theoryText: "The Galactic Council must approve a fuel transfer transaction. Station Alpha wants to send 500 Fuel Units to Station Beta. Audit the voting nodes and calculate final balances.",
        practical: {
          type: "server-audit",
          title: "Galactic Council Consensus Game",
          setupText: "Transaction Details:\n- Station Alpha Actual Balance: 600 Fuel Units\n- Quorum Rule: Simple majority (at least 3 out of 5 nodes) must agree.\n\nNode Votes:\n- Node 1: Vote Approve (Reports balance is 600)\n- Node 2: Vote Approve (Reports balance is 600)\n- Node 3: Vote Approve (Reports balance is 600)\n- Node 4 (Out of Sync): Vote Reject (Reports balance is 400)\n- Node 5 (Malicious): Vote Reject (Reports balance is 300)",
          question: "1) How many nodes Approve?\n2) How many Reject?\n3) Does it reach consensus? (yes/no)\n4) What is Station Alpha's final balance?",
          correctAnswer: "3:2:yes:100",
          debriefText: "Outstanding consensus resolution! The Navigation System is online and calibrated. You have mastered the Byzantine Generals Problem, PoW vs. PoS, Federated Consensus, and transaction ordering.",
          inputs: [
            { label: "Approve votes count", placeholder: "e.g. 3", key: "approve" },
            { label: "Reject votes count", placeholder: "e.g. 2", key: "reject" },
            { label: "Reaches consensus? (yes/no)", placeholder: "yes/no", key: "consensus" },
            { label: "Alpha final balance", placeholder: "e.g. 100", key: "bal_a" }
          ]
        }
      }
    ]
  },
  {
    id: 8,
    title: "MODULE 08",
    topic: "Immutability, Transparency & Blockchain Use Cases",
    stageName: "Eternal Night",
    iconName: "night",
    color: "#0ea5e9",
    angle: -135,
    rocketComponent: "ðŸ§‘â€ðŸš€ Command Module",
    description: "Verify shipping logs using traceability, calculate throughput costs comparing DB to BC, match industry use cases, and sort database architecture models.",
    tasks: [
      {
        id: "task8_1",
        title: "Task 8.1 â€” Immutability, Transparency, and Traceability",
        concept: "Blockchain core benefits",
        theoryText: "Why accept blockchain's tradeoffs? It yields three key benefits:\n\n1. Immutability: Chronological block dependency makes past edits computationally impossible.\n2. Transparency: Every account, transfer, and block is public and auditable.\n3. Traceability: Chronological append-only logs let you trace provenance of assets back to their genesis.",
        practical: {
          type: "inspector",
          title: "Rare Dilithium Supply Chain Audit",
          setupText: "Verify if shipping logs trace back to the Martian mine:\n\n- Tx 1: G_MARS_MINE_01 mints 50 units. (Hash: 0xMINT)\n- Tx 2: G_MARS_MINE_01 sends 50 units to G_SHIPPING_CORP. (Hash: 0xSHIP)\n- Tx 3: G_SHIPPING_CORP sends 30 units to G_STATION_BETA. (Hash: 0xDELIVER)\n- Tx 4: G_SMUGGLER_VOID sends 10 units to G_STATION_BETA. (Hash: 0xILLEGAL)",
          question: "1) Is the dilithium in Tx 3 authentic? (yes/no)\n2) Which transaction hash represents the illegal smuggling attempt?",
          correctAnswer: "yes:0xILLEGAL",
          debriefText: "Correct! Because blockchain records are transparent and traceable, you easily traced the cargo back to the original licensed Martian mine, exposing the smuggler's parallel payment attempt.",
          inputs: [
            { label: "Is Tx 3 authentic? (yes/no)", placeholder: "yes/no", key: "authentic" },
            { label: "Illegal transaction hash", placeholder: "e.g. 0xILLEGAL", key: "illegal" }
          ]
        }
      },
      {
        id: "task8_2",
        title: "Task 8.2 â€” The Disadvantages of Blockchain",
        concept: "Analyzing trade-offs",
        theoryText: "Blockchain has serious drawbacks:\n1. Speed & Scalability: Bitcoin does 7 TPS, Ethereum ~15-30 TPS. Centralized DBs do millions.\n2. Storage Bloat: Ledger size grows forever. Full nodes require massive SSD storage.\n3. Cost: Every transaction requires fee payments to validators.\n4. Absolute User Responsibility: Lost private keys mean lost funds forever.",
        practical: {
          type: "math-console",
          title: "The Trade-Off Calculator",
          setupText: "System Statistics:\n- Centralized: 5,000 writes/second. Cost: $0.0001 per write.\n- Proposed Blockchain: max 15 TPS. Fee: $1.20 per transaction.",
          question: "1) Can the blockchain handle a ticketing launch needing 20,000 sales in 10 seconds? (yes/no)\n2) What is the max TPS of the blockchain?\n3) What is the cost in dollars to write 1,000 transactions on the blockchain compared to the centralized DB? (truncate decimal values)",
          correctAnswer: "no:15:1199",
          debriefText: "Correct! For high-speed, high-volume, and low-cost systems with no trust issues, a traditional database remains the only viable choice.",
          inputs: [
            { label: "Can handle ticket launch? (yes/no)", placeholder: "yes/no", key: "handle" },
            { label: "Max TPS", placeholder: "e.g. 15", key: "tps" },
            { label: "Cost difference (dollars)", placeholder: "e.g. 1199", key: "cost" }
          ]
        }
      },
      {
        id: "task8_3",
        title: "Task 8.3 â€” Real-World Blockchain Applications",
        concept: "Matching industry solutions",
        theoryText: "Blockchain solves major real-world problems: Cross-Border Payments (fast, low-cost international settlements), Asset Tokenization (representing physical property as fractional digital shares), Digital Credentials (auditable diplomas), and DeFi (permissionless lending markets).",
        practical: {
          type: "drag-drop",
          title: "Real-World Problem Solver",
          setupText: "Match these 4 problems to their blockchain solution indices:\n\n1. A humanitarian agency distributes aid directly to refugees without banks -> Stablecoins / Stellar Network\n2. An art collector buys a fractional share (1%) of a painting -> Tokenization / NFTs\n3. A luxury watch brand proves a watch is authentic, not counterfeit -> Supply Chain Tracking\n4. A developer builds a permissionless lending market without credit checks -> Decentralized Finance (DeFi)",
          question: "Match problems 1-4 to solutions. (Enter matching sequence indices in order, e.g. 1234)",
          correctAnswer: "1234",
          debriefText: "Correct! These use cases succeed because they directly solve the problem of trust, access, and auditability between multiple independent parties.",
          inputs: [
            { label: "Match Sequence Code", placeholder: "e.g. 1234", key: "match" }
          ]
        }
      },
      {
        id: "task8_4",
        title: "Task 8.4 â€” Database vs. Blockchain Decision Matrix",
        concept: "Architecture decision tree",
        theoryText: "An architect follows a strict decision tree:\n1. Do multiple parties write? Yes -> Continue. No -> Database.\n2. Do writers trust each other? Yes -> Shared Database. No -> Continue.\n3. Is a middleman acceptable? Yes -> API/Database. No -> Blockchain.\n\nUse blockchain only when there are multiple untrusting writers with no central authority.",
        practical: {
          type: "validator-terminal",
          title: "Architecture Flow Solver",
          setupText: "Align the decision matrix checks: Q1 (Do multiple parties write?), Q2 (Do writers trust each other?), Q3 (Is a middleman acceptable?). When completed, the system registers the verification code.",
          question: "Run 'verify' to compile decision configurations. Enter the confirmation code (MATRIX_PASS).",
          correctAnswer: "MATRIX_PASS",
          debriefText: "Correct. This decision logic prevents over-engineering and keeps project architectures clean and efficient.",
          inputs: [
            { label: "Confirmation Code", placeholder: "e.g. MATRIX_PASS", key: "code" }
          ]
        }
      },
      {
        id: "task8_5",
        title: "Task 8.5 â€” Chapter Challenge: Choose Mercury's Technology",
        concept: "Categorizing software models",
        theoryText: "Determine database architectures for 8 applications. Categorize them as DB (Traditional Database), BC (Blockchain), or NONE (No database needed).",
        practical: {
          type: "server-audit",
          title: "Database Classification Matrix",
          setupText: "Applications:\n1. Instagram Clone (Photos, social graphs)\n2. Hospital Patient Records (Cross-hospital audit logs)\n3. Calculator App (Simple additions)\n4. Cross-Border Remittances (International asset transfers)\n5. University Attendance Logger (Class records)\n6. Supply Chain Origin Tracker (Diamond provenance)\n7. Food Delivery App (Menus and order dispatches)\n8. Digital Art Marketplace (Ownership registry)",
          question: "Enter the classification codes (DB, BC, or NONE) separated by colons in sequence (e.g. DB:BC:NONE:BC:DB:BC:DB:BC).",
          correctAnswer: "DB:BC:NONE:BC:DB:BC:DB:BC",
          debriefText: "Congratulations! The Command Module is fully installed and booted. The rocket is complete. You have mastered blockchain fundamentals, use-case selection, and trade-offs. Prepare for the final launch challenge!",
          inputs: [
            { label: "Instagram Clone", placeholder: "DB / BC / NONE", key: "c1" },
            { label: "Hospital Records", placeholder: "DB / BC / NONE", key: "c2" },
            { label: "Calculator App", placeholder: "DB / BC / NONE", key: "c3" },
            { label: "Cross-Border Remittances", placeholder: "DB / BC / NONE", key: "c4" },
            { label: "University Attendance", placeholder: "DB / BC / NONE", key: "c5" },
            { label: "Supply Chain Tracker", placeholder: "DB / BC / NONE", key: "c6" },
            { label: "Food Delivery App", placeholder: "DB / BC / NONE", key: "c7" },
            { label: "Digital Art Marketplace", placeholder: "DB / BC / NONE", key: "c8" }
          ]
        }
      }
    ]
  }
];

export interface FinalChallengeDef {
  id: number;
  title: string;
  type: "text" | "choice";
  question: string;
  choices?: string[];
  correctAnswer: string;
  setupText: string;
}

export const MERCURY_FINAL_CHALLENGES: FinalChallengeDef[] = [
  {
    id: 1,
    title: "Challenge 1: The Centralization Trap",
    type: "choice",
    setupText: "You are locked out of the core computer because the centralized validation server crashed.",
    question: "Identify the main vulnerability term of this setup.",
    choices: [
      "low processing speed",
      "insufficient database capacity",
      "single point of failure",
      "lack of client authentication"
    ],
    correctAnswer: "single point of failure"
  },
  {
    id: 2,
    title: "Challenge 2: Audit the Oxygen Air-Lock Logs",
    type: "choice",
    setupText: "Initial Balances: Station A = 100, Station B = 50, Station C = 10.\n\nTransactions:\n1. A sends 30 to B\n2. B sends 40 to C\n3. C sends 60 to A (C only has 50 after Tx2)",
    question: "Identify which transaction ID index (1-3) is invalid due to insufficient funds.",
    choices: ["1", "2", "3"],
    correctAnswer: "3"
  },
  {
    id: 3,
    title: "Challenge 3: Arrange the Block Sequence",
    type: "choice",
    setupText: "Scrambled Pointers:\n- Block Alpha | Hash: 0x1111, Prev: 0x0000\n- Block Beta  | Hash: 0x3333, Prev: 0x2222\n- Block Gamma | Hash: 0x4444, Prev: 0x3333\n- Block Delta | Hash: 0x2222, Prev: 0x1111",
    question: "Select the correct chronological block path from first to last.",
    choices: [
      "Alpha -> Beta -> Delta -> Gamma",
      "Alpha -> Delta -> Beta -> Gamma",
      "Delta -> Alpha -> Beta -> Gamma",
      "Beta -> Gamma -> Alpha -> Delta"
    ],
    correctAnswer: "Alpha -> Delta -> Beta -> Gamma"
  },
  {
    id: 4,
    title: "Challenge 4: Compute the Block Seal Hash",
    type: "text",
    setupText: "To seal the block, you must run the block hash command in the terminal.\n\nInputs:\n- height = \"4\"\n- timestamp = \"1782200000\"\n- prev_hash = \"0x3333\"\n- nonce = \"12\"\n\nString structure: height + timestamp + prev_hash + nonce",
    question: "Run command `sha256(\"417822000000x333312\")` in terminal to find the block hash output.",
    correctAnswer: "a9b8e2f1"
  },
  {
    id: 5,
    title: "Challenge 5: Find the Tampered Block",
    type: "choice",
    setupText: "The network reports validation errors. A past block has been tampered with, invalidating all subsequent blocks.",
    question: "An attacker modified Block 3's contents. Which block is the source of the validation break?",
    choices: ["Block 1", "Block 2", "Block 3", "Block 4", "Block 5"],
    correctAnswer: "Block 3"
  },
  {
    id: 6,
    title: "Challenge 6: Repair the Pointers",
    type: "text",
    setupText: "You have reverted Block 3's data. Its hash returns to 0xDDDD.",
    question: "What hash value must be inputted in Block 4's prev_block_id field to repair the chain link?",
    correctAnswer: "0xDDDD"
  },
  {
    id: 7,
    title: "Challenge 7: Configure Peer Connections",
    type: "choice",
    setupText: "Gossip protocols fail to propagate transactions due to loose peer-to-peer links.",
    question: "Which configuration ensures fault-tolerant transaction propagation?",
    choices: [
      "All nodes connect to a single central hub node",
      "Nodes are fully meshed in a meshed distributed topology",
      "Nodes remain isolated without sharing transactions",
      "Nodes only connect to one direct ancestor node"
    ],
    correctAnswer: "Nodes are fully meshed in a meshed distributed topology"
  },
  {
    id: 8,
    title: "Challenge 8: Restore Consensus Quorum",
    type: "choice",
    setupText: "Quorum consists of 5 validator nodes. 3 nodes vote to approve the block, while 2 nodes reject it.",
    question: "Do you Approve or Reject the block under BFT rules?",
    choices: ["Approve", "Reject"],
    correctAnswer: "Approve"
  },
  {
    id: 9,
    title: "Challenge 9: Choose the Launch Database",
    type: "choice",
    setupText: "The telemetry coordinates database must store launching configurations. It is controlled internally by one launchpad ground crew.",
    question: "Should this coordinate storage use a Blockchain or a Traditional Database?",
    choices: ["Blockchain", "Traditional Database"],
    correctAnswer: "Traditional Database"
  },
  {
    id: 10,
    title: "Challenge 10: Ignite the Core",
    type: "text",
    setupText: "The final engine ignition key is the SHA-256 hash output of the word \"LAUNCH\" in all caps.",
    question: "Run command `sha256(\"LAUNCH\")` in terminal to get the final hash value.",
    correctAnswer: "e527a8f1"
  }
];

